Fix `Pluck` example #439
go-gorm/gorm.io pull request #443
Opened 2021-07-27 22:45 UTC by s-takehana

- [x] **ONLY** change English documents in the Pull Request, translations will be synced and translate them with https://translate.gorm.io/ or it will cause merge conflicts!

### What did this pull request do?

Fix #439

2021-07-29 03:07 UTC, a631807682 requested changes
This problem not only in here, but also in the following document.
```
pages/docs/create.md
pages/docs/hooks.md
pages/docs/performance.md
pages/docs/query.md
pages/docs/sql_builder.md
pages/docs/update.md
pages/docs/v2_release_note.md
```

2021-08-01 08:53 UTC, s-takehana commented
@a631807682 Thank you for information. Let me confirm one thing.
Do you mean `Select([]string{"name", "age"})` is much better than `Select("name", "age")` ?
It seems both are fine.

GORM version is `v1.21.12` .
```go
package main

import (
	"fmt"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

type User struct {
	gorm.Model
	Name string
	Age  uint
}

func main() {
	dsn := "host=postgres user=postgres password=***** dbname=postgres port=5432"
	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})
	if err != nil {
		panic("failed to connect database")
	}

	db.AutoMigrate(&User{})

	db.Create(&[]User{
		{Name: "User1", Age: 20},
		{Name: "User2", Age: 20},
	})

	var users []User

	db.Debug().Model(&User{}).Select("name", "age").Scan(&users)
	fmt.Printf("%+v\n", users)

	db.Debug().Table("users").Select([]string{"name", "age"}).Scan(&users)
	fmt.Printf("%+v\n", users)

	db.Debug().Select("name", "age").Find(&users)
	fmt.Printf("%+v\n", users)

	db.Debug().Select([]string{"name", "age"}).Find(&users)
	fmt.Printf("%+v\n", users)
}
```

```
2021/08/01 08:46:05 /workspace/main.go:31
[0.794ms] [rows:2] SELECT "name","age" FROM "users" WHERE "users"."deleted_at" IS NULL
[{Model:{ID:0 CreatedAt:0001-01-01 00:00:00 +0000 UTC UpdatedAt:0001-01-01 00:00:00 +0000 UTC DeletedAt:{Time:0001-01-01 00:00:00 +0000 UTC Valid:false}} Name:User1 Age:20} {Model:{ID:0 CreatedAt:0001-01-01 00:00:00 +0000 UTC UpdatedAt:0001-01-01 00:00:00 +0000 UTC DeletedAt:{Time:0001-01-01 00:00:00 +0000 UTC Valid:false}} Name:User2 Age:20}]

2021/08/01 08:46:05 /workspace/main.go:34
[0.612ms] [rows:2] SELECT name,age FROM "users"
[{Model:{ID:0 CreatedAt:0001-01-01 00:00:00 +0000 UTC UpdatedAt:0001-01-01 00:00:00 +0000 UTC DeletedAt:{Time:0001-01-01 00:00:00 +0000 UTC Valid:false}} Name:User1 Age:20} {Model:{ID:0 CreatedAt:0001-01-01 00:00:00 +0000 UTC UpdatedAt:0001-01-01 00:00:00 +0000 UTC DeletedAt:{Time:0001-01-01 00:00:00 +0000 UTC Valid:false}} Name:User2 Age:20}]

2021/08/01 08:46:05 /workspace/main.go:37
[0.351ms] [rows:2] SELECT "name","age" FROM "users" WHERE "users"."deleted_at" IS NULL
[{Model:{ID:0 CreatedAt:0001-01-01 00:00:00 +0000 UTC UpdatedAt:0001-01-01 00:00:00 +0000 UTC DeletedAt:{Time:0001-01-01 00:00:00 +0000 UTC Valid:false}} Name:User1 Age:20} {Model:{ID:0 CreatedAt:0001-01-01 00:00:00 +0000 UTC UpdatedAt:0001-01-01 00:00:00 +0000 UTC DeletedAt:{Time:0001-01-01 00:00:00 +0000 UTC Valid:false}} Name:User2 Age:20}]

2021/08/01 08:46:05 /workspace/main.go:40
[0.344ms] [rows:2] SELECT "name","age" FROM "users" WHERE "users"."deleted_at" IS NULL
[{Model:{ID:0 CreatedAt:0001-01-01 00:00:00 +0000 UTC UpdatedAt:0001-01-01 00:00:00 +0000 UTC DeletedAt:{Time:0001-01-01 00:00:00 +0000 UTC Valid:false}} Name:User1 Age:20} {Model:{ID:0 CreatedAt:0001-01-01 00:00:00 +0000 UTC UpdatedAt:0001-01-01 00:00:00 +0000 UTC DeletedAt:{Time:0001-01-01 00:00:00 +0000 UTC Valid:false}} Name:User2 Age:20}]
```

2021-08-02 02:15 UTC, a631807682 commented
It seems I used an old version, it generate sql like this, i have just tested the code above is no problem.
```
 SELECT `name` = "age" FROM "users"
```

2021-08-05 09:20 UTC, s-takehana commented
@a631807682 I see.

2021-08-05 09:25 UTC, s-takehana commented on pages/docs/advanced_query.md
> +db.Model(&User{}).Select([]string{"name", "age"}).Scan(&users)
`Scan` requires `Model` or `Table`.

2021-08-09 05:09 UTC, jinzhu commented
The old style should works?

2021-08-09 05:09 UTC, closed without merging